### ISSUE TITLE
Extension Functions to Replace the "utils" package

### ISSUE THREAD

**Issue by Arham4** [nshusa/battlerune-server#1]
According to [the Kotlin docs](https://kotlinlang.org/docs/reference/extensions.html#motivation), extension functions were primarily made to replace the creation of "*Util" files. Consider revising the util files to better fit the Kotlin practice.

**Comment by nshusa** [comment]
@Arham4 Interesting! Did not know that. Thanks

**Comment by Arham4** [comment]
Have submitted pull request. (: https://github.com/nshusa/battlerune-server/pull/2
